[package]
name = "transformer"
version = "0.1.0"
edition = "2024"

[dependencies]
candle-core = { git = "https://github.com/huggingface/candle.git", version = "0.8.4" }
candle-nn = { git = "https://github.com/huggingface/candle.git", version = "0.8.4" }
tokenizers = "0.21.1"
